name: Festival
author: Genboy
version: 2.0.0
main: genboy\Festival\Festival
load: POSTWORLD
api: [3.0.0]
website: "https://github.com/genboy/Festival"
commands:
  fe:
    description: "Allows you to manage Festival area's and events."
    usage: "\n§dFestival Commands & options \n§bAcces Menu: §f/fe menu(ui/form) \n§bChoose language: §f/fe lang <en/nl/es/pl> \n§bToggle floating area titles: §f/fe titles \n§bSee area info at location: §f/fe <list/here> \n§5Create cube area: §f/fe pos1 §6select 1 corner, §f/fe pos2 §6select opposit diagonal corner and §f/fe create <AREANAME> §6to name the area. \n§5Create sphere area: §f/fe pos1 §6select radius or diameter start, §f/fe rad(darius) §6select radius distance or §f/fe dia(diameter) §6select diameter direction and distance and §f/fe create <AREANAME> §6to name the area. \n§6Delete area: §f/fe del(delete) <AREANAME> \n§9Flags: §fhurt, pvp, flight, edit, touch, mobs, animals, effects, msg, pass, drop, tnt, fire, explode, shoot, hunger, perms, fall, cmd \n§9Toggle area flags: §f/fe <FLAGNAME> <AREANAME> \n§5Add an area event command: \n§f/fe command <AREANAME> <add/enter/center/leave> <COMMANDID> <COMMANDSTRING> \n§5Edit or delete command: \n§f/fe command <AREANAME> <(edit)/del> <COMMANDID> (<COMMANDSTRING>) \n§5Change command event: \n§f/fe command <AREANAME> event <COMMANDID> <enter/center/leave> \n§5Whitelist players: \n§f/fe whitelist <AREANAME> <add/remove> <PLAYERNAME>"
    permission: festival.command.fe
permissions:
  festival:
    description: "Allows access to all Festival features."
    default: false
    children:
      festival.access:
        description: "Allows access to editing festival areas and events."
        default: op
      festival.command:
        description: "Allows access to all Festival commands."
        default: false
        children:
          festival.command.fe:
            description: "Allows access to the Festival area command."
            default: op
            children:
              festival.command.fe.lang:
                description: "Allows access to the Festival lang subcommand."
                default: op
              festival.command.fe.priority:
                description: "Allows access to the Festival priority subcommand."
                default: op
              festival.command.fe.titles:
                description: "Allows access to the Festival titles subcommand."
                default: op
              festival.command.fe.pos1:
                description: "Allows access to the Festival pos1 subcommand."
                default: op
              festival.command.fe.pos2:
                description: "Allows access to the Festival pos2 subcommand."
                default: op
              festival.command.fe.rad:
                description: "Allows access to the Festival radius subcommand."
                default: op
              festival.command.fe.dia:
                description: "Allows access to the Festival diameter subcommand."
                default: op
              festival.command.fe.create:
                description: "Allows access to the Festival create subcommand."
                default: op
              festival.command.fe.list:
                description: "Allows access to the Festival list subcommand."
                default: op
              festival.command.fe.here:
                description: "Allows access to the Festival here subcommand."
                default: op
              festival.command.fe.tp:
                description: "Allows access to the Festival tp subcommand."
                default: op
              festival.command.fe.rename:
                description: "Allows access to the Festival rename subcommand."
                default: op
              festival.command.fe.desc:
                description: "Allows access to the Festival description subcommand."
                default: op
              festival.command.fe.scale:
                description: "Allows access to the Festival scale subcommand."
                default: op
              festival.command.fe.flag:
                description: "Allows access to the Festival flag subcommand."
                default: op
              festival.command.fe.delete:
                description: "Allows access to the Festival delete subcommand."
                default: op
              festival.command.fe.whitelist:
                description: "Allows access to the Festival whitelist subcommand."
                default: op
              festival.command.fe.command:
                description: "Allows access to the Festival command subcommand."
                default: op
